### ISSUE TITLE
Indexer

### ISSUE THREAD

**Issue by AndreasGassmann** [tzcolors/tzcolors#24]
It would be nice if we could get additional info:

## Initial Auction
- Number of bids
- Auctions where I placed a bid
- address, amount and time of all previous bids

## Color is owned
- What price was it sold at?
- address of owner
- address, amount and time of all previous bids
- How long was the auction?
- How many people participated?

## Auction
- Price it was sold for previously for all the previous auctions
- Starting price
- Number of bids
- address, amount and time of all previous bids
- Auctions where I placed a bid

**Comment by dcale** [comment]
Number of bids:
https://tzcolors-indexer.prod.gke.papers.tech/api/v1/auction/operations?entrypoint=bid&parameters.value=8120217918

Auctions where I placed a bid:
https://tzcolors-indexer.prod.gke.papers.tech/api/v1/auction/operations?entrypoint=bid&source=tz1PuipWs33aqS2KSG5k1qQtC6Dff1P1GBmM

address, amount and time of all previous bids:
https://tzcolors-indexer.prod.gke.papers.tech/api/v1/auction/operations?entrypoint=bid&parameters.value=8120217918
